name: salam_flutter
description: A new Flutter project.

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-87.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.13
  connectivity: ^3.0.6
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.3+1
  firebase_core_platform_interface: 4.5.1
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  flutter_typeahead: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  flutter_inappwebview: ^5.7.1
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.2
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+1
  share_plus: ^4.0.10
  fwfh_text_style: ^2.22.8+1
  expandable_bottom_sheet: ^1.1.1+1
  http: ^0.13.4
  chip_list: ^2.3.3+8
  ffi: ^2.0.1
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter






flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/"

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
  flutter:


    fonts:
      - family: Mukta Regular
        fonts:
          - asset: assets/fonts/mukta_regular.ttf
            style: italic
      - family: Mukta Bold
        fonts:
          - asset: assets/fonts/mukta_bold.ttf
            weight: 700


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true